---
branches:
  only:
  - source
language: ruby
rvm:
- 1.9.3
before_install:
- git config --global user.name "there4(via Travis CI)"
- git config --global user.email "craig@there4development.com"
before_script:
- export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
- bundle install
- rake setup_github_pages[$REPO_URL]
script:
- rake generate
after_script:
- rake deploy
env:
  global:
  - GH_REPO="there4/there4.github.com"
  - secure: "Vn4zW0cTipyjF7NfayvLwPdqOJFxbQYtuX0+pSS8jP2pTjeKh185b89JKQ4zdIJZaFpOwhKsPumo7ixF3MXx1HibW04LGblTjuBBZNf2/hObXAtJhcGjatfILoL8vTW8z20mByg3Nv3WSdZRpwG//o1hDhEM5ZpCj820CsAkDds="
